inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .git/**/*
    - .github/**/*
    - coverage/**/*
    - doc/**/*
    - gemfiles/*
    - tmp/**/*
    - vendor/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  CustomTransform:
    OmniAuth: omniauth

Style/NumericPredicate:
  Enabled: false
